name: 'Reusable workflow'
on:
  workflow_call:

jobs:
  test:
    name: 'reusable workflow'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2.3.4'
        name: 'checkout'
      - name: 'test'
        run: |
          echo "Reusable workflow - Test successful"
